# circleci does not support version 3.3 ~
version: "3.2"
services:
  app:
    container_name: "gobel-admin-client"
    build:
        context: "./app"
        dockerfile: "Dockerfile.ci"
    tty: true